export const validSubmission = {
  razonSocial: "PRUEBA LOCAL Empresa ficticia",
  nombreComercial: "Empresa de prueba",
  responsableStand: "Persona de prueba",
  telefonoStand: "+54 11 0000 0000",
  emailStand: "stand@example.invalid",
  nombreStand: "Stand de prueba",
  responsablePago: "Persona de prueba",
  telefonoPago: "+54 11 0000 0001",
  emailPago: "pagos@example.invalid",
  cuit: "30-12345678-1",
  condicionIVA: "Responsable Inscripto",
  formaPago: "Transferencia",
  detalleFactura: "Datos ficticios para una prueba local. Sin efectos comerciales.",
};
